package com.insighthub.job.handlers;

import com.insighthub.job.JobEntity;
import com.insighthub.job.JobExecutionEntity;
import com.insighthub.job.scheduler.JobHandlerResult;
import com.insighthub.job.scheduler.JobOutputHandler;
import com.insighthub.report.RunReportResult;
import com.insighthub.smtp.EmailSender;
import com.insighthub.smtp.SmtpServerEntity;
import com.insighthub.smtp.SmtpServerService;
import jakarta.mail.MessagingException;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Job output handler that emails report results as a file attachment.
 * <p>
 * This handler:
 * <ol>
 *   <li>Generates a file from the report result based on the job's output format (CSV, XLSX, or PDF)</li>
 *   <li>Creates an email attachment from the generated bytes</li>
 *   <li>Resolves the SMTP server (job-specific or first active global default)</li>
 *   <li>Sends the email with the attachment to the configured recipients</li>
 * </ol>
 * </p>
 *
 * <p>Implements Requirement 3: Job Types — Email (Attachment)</p>
 */
@Component
@RequiredArgsConstructor
public class EmailAttachmentHandler implements JobOutputHandler {

    private static final Logger log = LoggerFactory.getLogger(EmailAttachmentHandler.class);

    private final EmailSender emailSender;
    private final SmtpServerService smtpServerService;
    private final ReportResultFileGenerator fileGenerator;

    @Override
    public JobHandlerResult handle(JobEntity job, JobExecutionEntity execution, RunReportResult result) {
        log.info("EmailAttachmentHandler processing job id={}, report rows={}", job.getId(), result.getRowCount());

        try {
            // Step 1: Generate a file from the report result based on output format
            String outputFormat = job.getOutputFormat() != null ? job.getOutputFormat() : "CSV";
            String reportName = job.getReport() != null ? job.getReport().getName() : job.getName();

            ReportResultFileGenerator.GeneratedFile generatedFile =
                    fileGenerator.generate(result, outputFormat, reportName);

            // Step 2: Create an email attachment from the generated file bytes
            EmailSender.Attachment attachment = new EmailSender.Attachment(
                    generatedFile.filename(),
                    generatedFile.data(),
                    generatedFile.contentType()
            );

            // Step 3: Resolve SMTP server (job's configured server, or first active default)
            SmtpServerEntity smtp = resolveSmtpServer(job);
            if (smtp == null) {
                log.error("No SMTP server available for job id={}", job.getId());
                return JobHandlerResult.failure("No SMTP server available to send email");
            }

            // Step 4: Send the email with the attachment
            emailSender.sendEmail(
                    smtp,
                    job.getEmailTo(),
                    job.getEmailCc(),
                    job.getEmailBcc(),
                    job.getEmailSubject(),
                    job.getEmailMessage(),
                    job.getEmailFrom(),
                    job.getEmailReplyTo(),
                    List.of(attachment)
            );

            log.info("Email with attachment '{}' sent successfully for job id={} to: {}",
                    generatedFile.filename(), job.getId(), job.getEmailTo());

            return JobHandlerResult.success(generatedFile.filename(),
                    "Email sent with attachment: " + generatedFile.filename());

        } catch (MessagingException e) {
            log.error("Failed to send email for job id={}: {}", job.getId(), e.getMessage(), e);
            return JobHandlerResult.failure("Email send failed: " + e.getMessage());
        } catch (Exception e) {
            log.error("Unexpected error in EmailAttachmentHandler for job id={}: {}", job.getId(), e.getMessage(), e);
            return JobHandlerResult.failure("Unexpected error: " + e.getMessage());
        }
    }

    /**
     * Resolves the SMTP server to use for sending.
     * <p>
     * Priority:
     * <ol>
     *   <li>The job's explicitly configured SMTP server (if active)</li>
     *   <li>The first active SMTP server in the system (global default)</li>
     * </ol>
     *
     * @param job the job entity
     * @return the resolved SmtpServerEntity, or null if none available
     */
    private SmtpServerEntity resolveSmtpServer(JobEntity job) {
        if (job.getSmtpServer() != null && job.getSmtpServer().isActive()) {
            return job.getSmtpServer();
        }

        List<SmtpServerEntity> activeServers = smtpServerService.getAllActive();
        return activeServers.isEmpty() ? null : activeServers.get(0);
    }
}
