-- V12: Divisions
-- Adds divisions table and division_id foreign key to report_groups and users.

-- ============================================================
-- Divisions Table
-- ============================================================
CREATE TABLE divisions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(200),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Add division_id FK to report_groups
-- ============================================================
ALTER TABLE report_groups ADD COLUMN division_id BIGINT;
ALTER TABLE report_groups ADD CONSTRAINT fk_rg_division
    FOREIGN KEY (division_id) REFERENCES divisions(id);

-- ============================================================
-- Add division_id FK to users
-- ============================================================
ALTER TABLE users ADD COLUMN division_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_user_division
    FOREIGN KEY (division_id) REFERENCES divisions(id);
